ferdos_garden/apps/account/urls.py
from django.urls import path
from .views import RegisterUserView,LoginUserView,LogoutUser
app_name='account'

urlpatterns = [
    path('sign_up/',RegisterUserView.as_view(),name='sign_up'),
    path('login/',LoginUserView.as_view(),name='login'),
    path('logout/',LogoutUser.as_view(),name='logout')
]

ferdos_garden/ferdos_garden/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('apps.index.urls',namespace='index')),
    path("places/",include('apps.place.urls',namespace='places')),
    path("blog/",include('apps.blog.urls',namespace='blog')),
    path("contact_us/",include('apps.contact_us.urls',namespace='contact')),
    path("blogs/",include('apps.blog.urls',namespace='blogs')),
    path("acount/",include('apps.account.urls',namespace='account'))
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# handler404 = "apps.index.views.error_404_view"

ferdos_garden/templates/partials/loging_state.html
{% if user.is_authenticated %}
      <div class="col-sm-12 col-md-12 position-absolute" style="right:320px;top:150px;width:450px;">
      {% comment %} <div class='col-5 d-flex flex-wrap justify-contact-around '> {% endcomment %}
      <a class="btn btn-outline-light mr-1 col-7  text-center bt-style" href="">کاربر<span class="text-danger">{{user.first_name}}</span> خوش آمدید<span class="sr-only">(current)</span></a>
      <a class="btn btn-outline-light col-2 text-center bt-style" href=" {% url 'account:logout' %} ">خروج<span class="sr-only">(current)</span></a>
    {% comment %} </div> {% endcomment %}
      </div>
{% else %}
      {% comment %} <div class='col-7 d-flex flex-wrap justify-contact-around'> {% endcomment %}
      <div class="col-sm-12 col-md-12 position-absolute" style="right:320px;top:150px;width:450px;">
      <a class="btn btn-outline-light mr-1 col-4  text-center bt-style" href="{% url 'account:login' %}">ورود<span class="sr-only">(current)</span></a>
      <a class="btn btn-outline-light col-4  text-center bt-style" href="{% url 'account:sign_up' %}">ثبت نام<span class="sr-only">(current)</span></a>
      {% comment %} </div> {% endcomment %}
{% endif %}