ferdos_garden/apps/blog/urls.py
from django.urls import path
from .views import show_blogs,show_blog

app_name='blogs'

urlpatterns = [
    path('',show_blogs,name='_blogs'),
    path('<str:blog_slug>',show_blog,name='_blog')
]

ferdos_garden/apps/contact_us/urls.py
from django.urls import path
from .views import contact_us

app_name='contact'
urlpatterns = [
    path("",contact_us,name='contact_us'),
]

ferdos_garden/apps/index/urls.py
from django.urls import path
from apps.index.views import show_home


app_name='index'

urlpatterns = [
    path("",show_home,name='home')
]

ferdos_garden/apps/place/urls.py
from django.urls import path
from apps.place.views import show_places,ferdos_history,ferdos_path_garden,show_rules_prices

app_name='places'

urlpatterns = [
    path("",show_places,name='places'),
    path("ferdos_garden_history/",ferdos_history,name='history'),
    path('pdf/<str:filename>',ferdos_path_garden,name='pdf'),
    path('prices_rules/',show_rules_prices,name='price-rules')
]

ferdos_garden/ferdos_garden/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('apps.index.urls',namespace='index')),
    path("places/",include('apps.place.urls',namespace='places')),
    path("blog/",include('apps.blog.urls',namespace='blog')),
    path("contact_us/",include('apps.contact_us.urls',namespace='contact')),
    path("blogs/",include('apps.blog.urls',namespace='blogs')),
    path("acount/",include('apps.account.urls',namespace='account'))
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# handler404 = "apps.index.views.error_404_view"

ferdos_garden/templates/partials/navbar/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border border-dark menu-style">
    <a class="navbar-brand text-danger" href="#"><span class="garden">باغ فردوس</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link text-info" href=" {% url 'index:home' %} ">صفحه اصلی<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-info" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            معرفی باغ
          </a>
          <div class="dropdown-menu border-style" aria-labelledby="navbarDropdown">
            <a class="dropdown-item text-info border-style text-center" href=" {% url 'places:history' %} ">تاریخچه</a>
            <a class="dropdown-item border-style text-info text-center" href=" {% url 'places:places' %} ">بخش های باغ</a>
            <a class="dropdown-item border-style text-info text-center" href=" {% url 'places:pdf' 'fferdowsGardenPath.pdf' %} ">فایل مسیر یابی</a>
            <a class="dropdown-item border-style text-info text-center" href=" {% url 'places:price-rules' %} ">برنامه و قوانین و قیمت ها</a>
          </div>
        <li class="nav-item">
          <a class="nav-link text-info" href=" {% url 'blogs:_blogs' %} ">مقالات</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-info" href="#">خاطرات بازدید</a>
        </li>
        </li>

        <li class="nav-item">
            <a class="nav-link text-info" href="#"> آموزش و پژوهش</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-info mr-4" href=" {% url 'contact:contact_us' %}">تماس با ما</a>
      </li>
    </ul>
      <form class="form-inline  my-2 my-lg-0">
        <input class="form-control  ml-sm-5 border-style" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-info ml-sm-1 my-2 my-sm-0 border-style" type="submit">جست و جو</button>
      </form>
    </div>
  </nav>