ferdos_garden/apps/blog/urls.py
from django.urls import path
from .views import show_blogs,show_blog

app_name='blogs'

urlpatterns = [
    path('',show_blogs,name='_blogs'),
    path('<str:blog_slug>',show_blog,name='_blog')
]

ferdos_garden/ferdos_garden/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('apps.index.urls',namespace='index')),
    path("places/",include('apps.place.urls',namespace='places')),
    path("blog/",include('apps.blog.urls',namespace='blog')),
    path("contact_us/",include('apps.contact_us.urls',namespace='contact')),
    path("blogs/",include('apps.blog.urls',namespace='blogs')),
    path("acount/",include('apps.account.urls',namespace='account'))
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# handler404 = "apps.index.views.error_404_view"

ferdos_garden/apps/blog/models.py
from distutils.command.upload import upload
from email.policy import default
from tabnanny import verbose
from django.db import models
from django.utils import timezone




def upload_service_main_imgae(instance,filename):
    return f'image/article_image/{instance.blog_slug}/{filename}'

def upload_service_gallary_image(instance,filename):
    return f'image/article_gallery/{instance.blog.blog_slug}/{filename}'

#----------------------------------------------------------------------------------------
class Author(models.Model):
    author_name=models.CharField(max_length=50,verbose_name='name')
    author_family=models.CharField(max_length=50,verbose_name='family')
    author_slug=models.SlugField(max_length=50,verbose_name='slug')
    author_email=models.EmailField(max_length=255,verbose_name='email')
    author_phone=models.CharField(max_length=11,verbose_name='phone',null=True,blank=True)
    auhtor_status=models.BooleanField(default=False,verbose_name='status')
    
    def __str__(self):
        return self.author_name+' '+self.author_family
    
    class Meta:
        verbose_name='Author'
        verbose_name_plural='Authors'
        db_table='table_author'
 
#----------------------------------------------------------------------------------------
class BlogGroup(models.Model):
    group_title=models.CharField(max_length=50,verbose_name='title')
    
    def __str__(self):
        return self.group_title
    
    class Meta:
        verbose_name='BlogGroup'
        verbose_name_plural='BlogGroups'
        db_table='table_blogGroup'
        
#----------------------------------------------------------------------------------------
class Blog(models.Model):
    blog_title=models.CharField(max_length=50,verbose_name='title')
    blog_main_image=models.FileField(upload_to=upload_service_main_imgae,verbose_name='main_image')
    blog_slug=models.SlugField(max_length=50,verbose_name='slug')
    blog_short_text=models.TextField(verbose_name='short_text')
    blog_main_text=models.TextField(verbose_name='main_text')
    blog_register_date=models.DateTimeField(auto_now_add=True,verbose_name='register_date')
    blog_publish_date=models.DateTimeField(default=timezone.now,verbose_name='publish_date')
    blog_update_date=models.DateTimeField(auto_now=True,verbose_name='update_date')
    blog_status=models.BooleanField(default=False,verbose_name='status')
    blog_view_number=models.PositiveIntegerField(default=0,verbose_name='views')
    blog_author=models.ForeignKey(Author,on_delete=models.CASCADE,verbose_name='author')
    blog_group=models.ForeignKey(BlogGroup,on_delete=models.CASCADE,verbose_name='group')
    
    
    def __str__(self):
        return self.blog_title
    
    def blog_pgf(self,fileName):
        pass
    
    class Meta:
        verbose_name='Blog'
        verbose_name_plural='Blogs'
        db_table='table_blog'
     
#----------------------------------------------------------------------------------------    
class Tag(models.Model):
    tag_name=models.CharField(max_length=50,verbose_name='tag')
    blog=models.ManyToManyField(Blog)
    
    def __str__(self):
        return self.tag_name
    
    class Meta:
        verbose_name='Tag'
        verbose_name_plural='Tags'
        db_table='table_tag'
        
#----------------------------------------------------------------------------------------
class BlogGallary(models.Model):
    blog_image=models.FileField(upload_to=upload_service_gallary_image,verbose_name='main_image')
    blog=models.ForeignKey(Blog,on_delete=models.CASCADE,verbose_name='blog')
    
    def __str__(self):
        return self.blog.blog_slug
    
    class Meta:
        verbose_name='BlogGallary'
        verbose_name_plural='BlogGallarys'
        db_table='table_blogGallary'
        

#----------------------------------------------------------------------------------------
class Like(models.Model):
    pass
class DisLike(models.Model):
    pass

#----------------------------------------------------------------------------------------
class BlogIdea(models.Model):
    blog_slug=models.SlugField(max_length=100,verbose_name='blog_slug',null=True,blank=True)
    full_name=models.CharField(max_length=100,verbose_name='نام')
    email=models.EmailField(max_length=255,verbose_name='ایمیل')
    register_date=models.DateField(default=timezone.now,verbose_name='register_date')
    blog_idea=models.TextField(verbose_name='نظر')
    
    def __str__(self):
        return self.full_name
    
    class Meta:
        verbose_name='BlogIdea'
        verbose_name_plural='BlogIdeas'
        db_table='table_BlogIdea'

ferdos_garden/apps/blog/forms.py
from django import forms
from .models import BlogIdea


class BlogIdeaForm(forms.ModelForm):

            
    class Meta:
        model=BlogIdea
        fields=('full_name','email','blog_idea')
        widgets={
             'full_name':forms.TextInput(attrs={'class':'form-control shadow','style':'border:0;font-size: 20px;margin:10px;','PlaceHolder':'سارا'}),
             'email':forms.TextInput(attrs={'class':'form-control shadow','style':'border:0;font-size: 20px;margin:10px','PlaceHolder':'ایمیل'}),
             'blog_idea':forms.Textarea(attrs={'class':'form-control shadow','style':'border:0;font-size: 20px;margin:10px','PlaceHolder':'متن پیام'})
         }

ferdos_garden/apps/blog/views.py
from django.shortcuts import render
from .models import Blog,BlogGallary,Tag
from django.core.paginator import Paginator
from .models import BlogIdea
from .forms import BlogIdeaForm
from django.contrib import messages


#-------------------------------------------------
def show_blogs(request):
    blogs=Blog.objects.filter(blog_status=True)
    pagenator=Paginator(blogs,4)
    page_number=request.GET.get('page')
    page_object=pagenator.get_page(page_number)
    return render(request,'blogs/blogs.html',{'page_obj':page_object})

#-------------------------------------------------
def show_blog(request,blog_slug):
    blog=Blog.objects.get(blog_slug=blog_slug)
    blog_tag=Tag.objects.filter(blog__blog_slug=blog_slug)
    blog_gallery=BlogGallary.objects.filter(blog__blog_slug=blog_slug)
    blog_idea=BlogIdea.objects.filter(blog_slug=blog_slug)
    blog.blog_view_number=blog.blog_view_number+1
    form=BlogIdeaForm()
    blog.save()
    
    context={
        'blog':blog,
        'blog_tag':blog_tag,
        'blog_gallery':blog_gallery,
        'blog_idea':blog_idea,
        'form':form
    }
    
    if request.method=='POST':
        form_1=BlogIdeaForm(request.POST)
        if form_1.is_valid():
            new_form=form_1.cleaned_data
            final_form=BlogIdea()
            final_form.blog_slug=blog_slug
            final_form.full_name=new_form['full_name']
            final_form.email=new_form['email']
            final_form.blog_idea=new_form['blog_idea']
            blog.blog_view_number=blog.blog_view_number-1
            final_form.save()
            blog.save()
            return render(request,'blog/blog.html',context)
        else:
            blog.blog_view_number=blog.blog_view_number-1
            blog.save()
            context['form']=form_1
            return render(request,'blog/blog.html',context)
    else:
        return render(request,'blog/blog.html',context)

ferdos_garden/templates/blogs/blogs.html
{% extends 'main_template.html' %}

{% block title %}Blogs{% endblock title %}

{% block main %}
            {% for blog in page_obj %}
                <div class="d-flex justify-content-around flex-wrap col-10  my-4 mx-auto p-3 bt-style shadow">
                    <img src="{{media_url}}{{blog.blog_main_image}}" alt="{{blog.blog_slug}}" class='col-sm-12 col-lg-4 mx-sm-auto blog-image-style '>
                    <div class="col-sm-12 my-sm-3 col-lg-8 text-justify">
                        <h2>{{blog.blog_title}}</h2>
                        <span class="text-secondary">{{blog.blog_short_text}}</span>
                    </div>
                    <div class="col-sm-12 col-lg-2 p-2  mt-2 bt-style text-center shadow-sm">
                        {{blog.blog_group}}
                    </div>
                    <div class="col-sm-12 col-lg-5 p-2  mt-2 bt-style text-center shadow-sm">
                        <span>نویسنده :</span>&nbsp;<span class="text-secondary">{{blog.blog_author}}</span>
                    </div>
                    <div class="col-sm-12 col-lg-3 p-2  mt-2 bt-style text-center shadow-sm">
                        <span>تعداد بازدید کنندگان :</span>&nbsp;<span class="text-secondary">{{blog.blog_view_number}}</span>
                    </div>
                    <div class="col-sm-12 col-lg-1 p-auto pl-sm-0 pl-lg-4  mt-2 bt-style">
                        <a href=" {% url 'blogs:_blog' blog.blog_slug %} " class='btn btn-outline-primary bt-style'>ادامه</a>
                    </div>
                </div>  
            {% endfor %}




            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
        
                <!--Previous-->
                {% if page_obj.has_previous %}
                    <li class="page-item "><a class="page-link" href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                        {% endif %}
                <!-- Previous-->
        
                <!--Hellip-->
                {% if page_obj.number|add:'-4' > 1 %}
                    <li class="page-item"><a class="page-link " href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
                {% endif %}
        
            <!--Pager-->
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active text-dark" aria-current="page">
                        <span class="page-link">
                            {{ i }}
                            <span class="sr-only">(current)</span>
                        </span>
                    </li>
                {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            <!--end Pager__>
        
            <!Hellip-->
            {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                <li class="page-item"><a class="page-link " href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
            {% endif %}
            <!end Hellip -->
        
            <!--Next-->
            {% if page_obj.has_next %}
                <li class="page-item ">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">بعدی</a>
                </li>
            {% else %}
                <li class="page-item-disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="True">بعدی</a></li>
            {% endif %}
            <!--end Next-->
            </ul>
        </nav>
        
            <!-- end of pagination -->
{% endblock main %}